export const _getRouteParam = (req, name) => req.params[name];
export const _getRouteParams = (req) => req.params;
export const _getRoute = (req) => req.route.path;
export const _getBody = (req) => req.body;
export const _getBodyParam = (req, name) => req.body ? req.body[name] : null;
export const _getQueryParam = (req, name) => req.query ? req.query[name] : null;
export const _getCookie = (req, name) => req.cookies ? req.cookies[name] : null;
export const _getSignedCookie = (req, name) => req.signedCookies ? req.signedCookies[name] : null;
export const _getHeader = (req, field) => req.get(field);
export const _getHeaders = (req) => req.headers;
export const _accepts = (req, types) => req.accepts(types);
export const _acceptsCharset = (req, charset) => req.acceptsCharset(charset);
export const _acceptsLanguage = (req, language) => req.acceptsLanguage(language);
export const _hasType = (req, type) => req.is(type);
export const _getRemoteIp = (req) => req.ip;
export const _getRemoteIps = (req) => req.ips;
export const _getPath = (req) => req.path;
export const _getHostname = (req) => req.hostname;
export const _getSubdomains = (req) => req.subdomains;
export const _isFresh = (req) => req.fresh;
export const _isStale = (req) => req.stale;
export const _isXhr = (req) => req.xhr;
export const _getProtocol = (req) => req.protocol;
export const _getMethod = (req) => req.method;
export const _getUrl = (req) => req.url;
export const _getOriginalUrl = (req) => req.originalUrl;
export const _getData = (req, name) => req.userData ? req.userData[name] : null;
export const _setData = (req, name, val) => (req.userData = req.userData || {}, req.userData[name] = val);
